### ISSUE TITLE
0 Ohm resistor?

### ISSUE THREAD

**Issue by flagrange** [sarnau/Inside-The-Loxone-Miniserver#24]
Hello,
Your description for an external antenna on your Miniserver Go documentation mentions: "_move the 0Ω resistor connecting pin 31_". I'm not a great electronician, but I assume this is a typo? 

I assume you mean to basically turn the brownish resitor 90 degrees counterclockwise (on your picture), then connect the antenna to the two holes on the right?
Thank you,

![Antenna resistor](https://user-images.githubusercontent.com/41645019/101015135-36aad100-3567-11eb-8c44-8bad5782605e.JPG)

**Comment by sarnau** [comment]
That is the assumption. Not sure of the GND is correct.
