### ISSUE TITLE
Cannot format SD card with Loxone Config: Error 12

### ISSUE THREAD

**Issue by cmonty14** [sarnau/Inside-The-Loxone-Miniserver#25]
Hi,
I cannot format the SD card with Loxone Config; the error displayed is:
Fehler - 12 beim Formatieren

![loxmini_format](https://user-images.githubusercontent.com/12523591/101344802-56ebd000-3886-11eb-8875-a2ad4ea28fd1.png)

I have tried to format the SD card with several card readers w/o success.
Then I started to format the SD card with Windows tools, and this worked. Now the card is totally empty.

Can you advise how to fix this?

THX

**Comment by sarnau** [comment]
That is more a question for a Loxone forum, like [https://www.loxforum.com](https://www.loxforum.com). Anti-Virus software or something?

**Comment by cmonty14** [comment]
After formatting th SD card with Windows tools, the error message is now:
Fehler - 1 beim Formatieren

Can I still use the SD card although is is completely empty now?

**Comment by sarnau** [comment]
No idea, but if the SD card is not defect, it will be usable. But I am not using Windows.

**Comment by cmonty14** [comment]
I would prefer to use Linux OS, but then I must use Wine.
Do you know if I can format a SD card with Loxone Config in Wine?
Or can you recommend any other way to format the SD card?

**Comment by Woersty** [comment]
I know it's a bit late but I had the same. You need to be Admin when starting Loxone config and you must try it several times sometimes.

-1 means wrong file system format
It must be FAT32 but not NTFS.

-6 is for no file system

-2 reason is not known by me but if I have -2 it usually works with 2 or 3 tries.
