### ISSUE TITLE
Emulate Tree Device on real tree extension

### ISSUE THREAD

**Issue by challo2018** [sarnau/Inside-The-Loxone-Miniserver#3]
Hello Markus, 
sorry for asking again, but i'm still trying to get your code running.
Is it possible to emulate an single tree device (eg. tree motion sensor) and connect SM32 CAN to tree bus to get the emulated sensor running with real tree extension. In your example, the emulated tree device is running together with emulated tree extension.

Thanks, BR Fabian

**Comment by sarnau** [comment]
Yes, you can do a Tree Device only, just emulate that one without Tree Extension.

**Comment by challo2018** [comment]
Thanks for your quick reply.
So simply:
devices.append(LoxBusTreeAlarmSiren(canbus, 0xbb008012))

**Comment by sarnau** [comment]
I think that will do. Just make sure to not add any other LoxLink devices, that will mess up the CAN bus behind the Tree Extension.

**Comment by challo2018** [comment]
good point! I'll check if it's working.
Thanks!!

**Comment by chrisrock1984** [comment]
> Thanks for your quick reply.
> So simply:
> devices.append(LoxBusTreeAlarmSiren(canbus, 0xbb008012))

Hi,

I also tried Tree only device using -> static LoxBusTreeRgbwDimmer gLoxBusTreeRgbwDimmer(gLoxCANDriver, 0xb010035c, gResetReason);

but the device is not recognized by the miniserver
