### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by benjamintypzwo** [sarnau/Inside-The-Loxone-Miniserver#5]
Thank you for this great collection, it is really helpful.
I would like to implement the loxlink for AVR and I am curious about the supported Miniserver Firmare-Versions.
My Miniserver runs 9.1.10.30, I could report issues/changes in Protocol if I find some.

Which (max) version did you test?

Best regards

**Comment by sarnau** [comment]
The current version: 10.2.3.26
