### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by benjamintypzwo** [sarnau/Inside-The-Loxone-Miniserver#6]
Hallo Markus, erst einmal vielen Dank für deine Arbeit. Das ist alles sehr hilfreich.

Leider ist mir ausser per Issue kein Weg bekannt per Guthub Kontakt aufzunehmen.
Kannst du eventuell noch zusätzliche Ressourcen zur Verfügung stellen?

MfG Benamin (uC.net)

**Comment by sarnau** [comment]
Erledigt
