### ISSUE TITLE
Hardcoded IP-Address in Code

### ISSUE THREAD

**Issue by mschlenstedt** [sarnau/Inside-The-Loxone-Miniserver#8]
You have hardcoded your IP address here: https://github.com/sarnau/Inside-The-Loxone-Miniserver/blob/b36db3ed250805bfc66dd816d46b799c46f4e588/Code/LoxoneMonitorServer.py#L207

From my point of view it should be LOCAL_IP

**Comment by sarnau** [comment]
Good point, yes, that needs to be changed
